{% set name = "sixs" %}
{% set version = "1.1" %}
{% set sha256 = "4253664bfed35a659ac602d4472780df7c665d67021d495327f47eb7325a2d7e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/petebunting/6s/get/Version%201.1.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('cxx') }}            # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
  host:
  run:
    - m2w64-gcc-libgfortran  # [win]


test:
  files:
  - Example_In_1.txt

about:
  home: https://bitbucket.org/petebunting/6s
  summary: A basic RT code used for atmospheric correction & atmospheric
    simulations
  license: MIT
  license_family: MIT
  description:  |
    The 6S code is a basic RT code used for calculation of lookup
    tables in the MODIS atmospheric correction algorithm.
    It enables accurate simulations of satellite and plane observation,
    accounting for elevated targets, use of anisotropic and lambertian surfaces
    and calculation of gaseous absorption. 6S website is http://6s.ltdri.org.

extra:
  recipe-maintainers:
    - robintw
    - danclewley
