appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HQvX+U8SkabfldH/YLBOZrAaGWRkMIkYo9v1mj+00L5fEjN/31NDWrB/8FBn+gPi2OKAgmnzx4Vv9wt1fr13hhVUzXxqoLIoQDwzkaUWyYWBMQF5v/61W18JtwYnVgaXMouLUq2HMkeTZSp8fIKqel8HsdpAl3fgZz1/pgP2mfMZSbhRNKKQ732CLRPb/q7QiEgou5ic0fphCw7Io7eVtSBz+hH70+b7CpqyQ/qoDrkkYprbl0r4GgHC+zKr1Ybr3bjvp5h5bluqx0EDZc8eRMX/iS2oYplDf/D4dEhuI71lYWMP1a73WjaQ5q6sXScl1ylPOp7E9irrTCr0bkL/NlUYeuy8Xa6LhjfuhUnQE+vesc4kvA1PX8TyQaoOTWr2lGXMHTNfl5RQeVBYg1nElNXhhkweFWSbBcMv1+ti9OY8b0pFTqtTCLGFwhUGn3Rg3NGb7/ZFhSP2G2rBnbeMu4Lohv4xcT8CFJ61UNm+vrisOrHf7b2uVR+V+I4FK6n2xw+hl/fi/t3Ch68WQXNlAfnO5zTwAmQuEUgDyJuRY/DxYiCcua9ZvOTGUBkLHVpc2o1/hCvwwTGXma3z2UkcfQSmTkYrLOCdzFucUuC0Dhy0f+ltC+fjYzWqlfoMAGPLzuGN0K+kUIapJPXTLZhXfXbt3W4vq+0RLF8FxP3pILA=}
conda_forge_output_validation: true
