travis:
  secure:
    BINSTAR_TOKEN: NIdssFjXnYWU6kg4HgF9Dei9pbZ6jeBDrT9QCD8x3wZNMJL53VagEl9imiY1dfb883YWa2c7UxdS88KkcBD1u/wniWbRL2HdrA7qVHPVK442raHvUKuOspzpkqNEUe2TWAiIALME3I6RvoL9TPEm+Nj9TSfaseVeJ9jgoOYlLBnC68cyY1qJIZpzWwH/t+N0Q2yXxjs5wFSDxnl2L/GPSoFuXNQE9fhda3qQAHJkWZcdCWhqQL6QGj9NidkVdgWwvlppp+CoREHQxhwkLy5SFhVhmO0v1xFVqnSQJ1XKczaERPr94OzA1Nmes4M3H9MwrDEAkbvmCcIZWCsY1FCnN43Z08TxPv9mt7Vfc+JtUD84e2PD6LuwNDawl1pk7lTubRN+fGdDXyWnkyCn4CGeHLyy6O99oEQESiTjv04YsX4+1a4CR509zIpy44MR8geJ8wmVbYG7aSNz1mw+WKGQ+hF2Feb7cjTsX+GBWrBmTSKXQBS1aGKyLPeDygvIDO1oahRhui6SMLfsmblbASKPhbw+cC9uped6i8OeNoEwqlaDKl32LIfnqWHPasnCukLReQKfG6n1LAX1ejajnSjxPRkWfFIMmnefmMDL6T9VN+pnokCi591B1jG7CK3jW7HNKsD1ZV+qfS/8HyfCR1MqJ/vaU4evklMeX6f4EexB2V0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
