travis:
  secure:
    BINSTAR_TOKEN: US5Dw5Z+lWoB4zNkKyYlpwpH6CGAgin3gmLpDInfGyEoc1kQhmXq+9UDM/5dyoRKcigFrlHq27SrUNBi87FpesVUO5ir3i6sdEAMFjv/rBOGrY77y/NtOJtjScSQTaiunQg9Cbh84kqxFrcHR4kzAzwEa95rTXl1Jc2/SnTvSJFDCdEojsUMEpI5yigMcQnLAfSXONrZyYuXf7FwvYXxKS/1I7QJRngZBcPSYauqMfWRInsWBnbnaS/ZtyNXG7KO4YtaHhdUky0QomyoCdw2+dBm9ZFC8sHSSM4EFMveT6+aI4NM5Wn/MRoAew1EBmRAZ10LXEeMbrmv9mk0jNCQAFr0gQnAw0fTzRvEnv3/byO2MXYWZdvgHy395dgVRIF/ZNuT1rminv2LzjweUrduKhgF8m8PpD9KlsuswNK+52sz2OgORIp07ZhlbeVSI2nQfAMBQ1TmYZhGq0+uIKXQ7jk5sW3MkU6qA0gYsYy3ExTbMB0A+Hl65/plfBx6z5eDLANEVdnlav5zdmMQWA+Dzlofv1/kzwHbtippZP0B2fk7WHss3P/Kb/mphZcSJeNkJ+p67cwiwarFrdbgluJG07DRjEjm1EG8fzTyym/lMEBExxvJ/hZq1Z4H7HjKBwYBA+/TZ0uTr8QQZh2yhIajKGwmkif88MD8X9Be5TrrfEY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
